"use client";

import type { Metadata } from "next";
import "./globals.css";
import { PrivyProvider } from "@privy-io/react-auth";
import { Suspense } from "react";
import MapboxMap from "@/components/map/MapboxMap";
import BottomNavigation from "@/components/navigation/BottomNavigation";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <>
          <PrivyProvider
            appId={process.env.NEXT_PUBLIC_PRIVY_APP_ID as string}
            config={{
              loginMethods: ["twitter", "google"],
              appearance: {
                theme: "dark",
                showWalletLoginFirst: false,
              },
            }}
          >
            {/* <h4>Application context (if needed)</h4> */}
            <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
          </PrivyProvider>
        </>
      </body>
    </html>
  );
}
